[package]
name = "tomfoolery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord_client = { path = "./client" }
ml_server = { path = "./model" }